### ISSUE TITLE
Broken / wrong links when no paid plan is configured

### ISSUE THREAD

**Issue by dogweather** [TryGhost/Themes#154]
### Issue Summary

As a new Ghost publisher, I'm not ready to connect to Stripe and configure the paid plans for members. I'm starting out with simple free sign-up.

Several UI bugs occur for site visitors in this state. When a signed-in visitor visits the site and there are no configured paid plans,

* In some themes, they get **Upgrade** buttons which display a broken dialog (Journal v1.0.0).
* They still see **Sign up** links (although signed up and logged in) Casper v5.3.1 and Journal v1.0.0 and probably others.

#### Here, a signed-in member is incorrectly shown the upgrade button in multiple places leading to a broken dialog (Journal v1.0.0 theme):

<img width="331" alt="Screen Shot 2022-08-31 at 3 18 45 AM" src="https://user-images.githubusercontent.com/150670/188252726-34d13651-b49a-4fd4-9f94-dfba51bafd09.png">

<img width="740" alt="Screen Shot 2022-09-02 at 8 44 27 PM" src="https://user-images.githubusercontent.com/150670/188252916-38dfca06-be05-4632-a7fd-b3f0e8bc3972.png">

#### Broken dialog:

<img width="536" alt="Screen Shot 2022-08-31 at 3 30 01 AM" src="https://user-images.githubusercontent.com/150670/188252739-410bb14a-54e0-4613-aa34-f8cd7607f6fc.png">

#### Here, a signed-up and signed-in free member is incorrectly shown the "Sign up" link (Casper theme):

<img width="1136" alt="Screen Shot 2022-09-02 at 8 18 00 PM" src="https://user-images.githubusercontent.com/150670/188252673-f5c1bacc-ee60-4210-9861-c1b51ea73596.png">

### Steps to Reproduce

1. Create new site with Journal theme.
2. Sign up as free tier member.
3. Browse to About page, see the Upgrade button.
4. See the Signup links in the footers and elsewhere.

### Ghost Version

Ghost(Pro)

### Node.js Version

unknown

### How did you install Ghost?

Pro

### Database type

Other

### Browser & OS version

Safari / current

### Code of Conduct

- [X] I agree to be friendly and polite to people in this repository

**Comment by ErisDS** [comment]
I have moved this issue into the Themes repo for @minimaluminium to take a loo at, as these are not issues with Ghost itself. However, I imagine this theme code pre-dates the new `@site.paid_members_enabled` flag & this is more "not implemented yet" rather than a bug per 
se. Previously, there was no way to tell if payments were enabled on a site, so each theme had payment handling either on or off.

**Comment by dogweather** [comment]
FYI, I've found this workaround for the **Dawn** theme: hiding "upgrade" elements via JS in the footer injection text field:

```javascript
<script>
    $('button.members-upgrade').css('display', 'none')
</script>
```

**Comment by dogweather** [comment]
> rather than a bug per se.

There are definitely several problems here. Maybe this should be split out into separate Issues. 

* One is logic errors in the templates. E.g., above, the signup text is shown regardless if the user is a @member.
* Another is incorrect messaging to 'upgrade' when it's not set up in Ghost.
* Another is broken dialogs shown to users who click these upgrade buttons.

Each makes the theme unusable in some way.

**Comment by minimaluminium** [comment]
Hey @dogweather, thanks for the detailed feedbacks here.

> the signup text is shown regardless if the user is a @member

The `Signup` link in the footer is added by the navigation and themes have no control over this. You'd want to replace this with a different link in the navigation settings if you don't want it to appear all the time.

> Another is incorrect messaging to 'upgrade' when it's not set up in Ghost

This is now fixed by checking if paid membership is setup with `{{#if @setting.paid_members_enabled}}`. All you need is now re-installing the theme.

> Another is broken dialogs shown to users who click these upgrade buttons

This won't be a problem anymore with the fix above.

**Comment by dogweather** [comment]
> Hey @dogweather, thanks for the detailed feedbacks here.

You're welcome, glad I could help. I had these problems while trialing Ghost Pro. I kept my blogs on wordpress.com for now. I'll circle back around and try again sometime.

**Comment by minimaluminium** [comment]
Thanks, closing the issue for now. You can re-open it anytime if any of the issues still remains.
