### ISSUE TITLE
[Headline] Lack of pagination or infinite scroll on latest post page

### ISSUE THREAD

**Issue by marithpl** [TryGhost/Themes#212]
Im building a new blog based on Ghost Headline theme.
99% of work is done except a `/page/2` page.

I wish to have a pagination there or working infinite scroll. But now when you go to `mydomain.com/page/2` there are loaded all posts (400+) with thumbnails. So that page is very heavy because a lot of resources are loaded.

Is it possible to enable pagination there?

I think by default there should be a Infinite Scroll - but it seems doesn't work.

**Comment by minimaluminium** [comment]
Hey @marithpl,

The main reason we used `/page/2` for the archive was making the theme work out of the box. So that users won't have to upload additional routing file for that feature.

To make the pagination work, you'll have to make some customzation to your Ghost site configuration and theme as well.

1. Add a channel route. Channel suits best in this situation, because it doesn’t modify post permalinks like collections do. And supports pagination as well. Restart your Ghost site if you need.

```yaml
routes:
  /archive/:
    controller: channel
```

2. Replace two instances of `/page/2` with `/archive` in `home.hbs`, so that it'd link to a correct URL on the homepage.

3. Modify `index.hbs` to remove the get helper and make it paginated. Current implementation fetches all posts and loops through them.

Before:
```hbs
{{#get "posts" include="authors" limit="all"}}
    <div class="gh-topic gh-topic-grid">
        <div class="gh-topic-content">
            {{#foreach posts}}
                {{> "loop-grid"}}
            {{/foreach}}
        </div>
    </div>
{{/get}}
```

After:
```hbs
<div class="gh-topic gh-topic-grid">
    <div class="gh-topic-content">
        {{#foreach posts}}
            {{> "loop-grid"}}
        {{/foreach}}
        {{pagination}}
    </div>
</div>
```

4. Finally, style the pagination with CSS. This is very basic styling, and you can style it as you want. It's recommended you add this as a code injection in `Settings > Code injection > Site Header` instead of updating the theme CSS directly.

```html
<style>
  .pagination {
    grid-column: 1/3;
    width: 100%;
  }
</style>
```

Now when you go to `yoursite.com/archive`, the posts will be paginated.
