### ISSUE TITLE
[London] Theme is broken

### ISSUE THREAD

**Issue by Nightapes** [TryGhost/Themes#214]
Hey Ghost Team, 

i found multiple Issues with the London Theme. It can be reproduced in here: https://london.ghost.io/

1. Navigation does not work when to many Items in the List, the Dropdown does not appear. 
<img width="895" alt="Screenshot 2023-01-12 at 17 12 44" src="https://user-images.githubusercontent.com/15911153/212120902-98bac439-d680-461c-80b5-2ac14e554774.png">

2. Mobile View of Menu is broken
   2.1 Close button missing
   2.2 Header is missing
   2.3 Space on the bottom
  <img width="643" alt="Screenshot 2023-01-12 at 17 14 35" src="https://user-images.githubusercontent.com/15911153/212121289-2466ea1b-f273-4944-86f1-3e16e06f72d5.png">

3. Development, i tried to make a dark version of London and changed the vars, but this did not work.
  It is a little bit strange to have a var  [--color-bg](https://github.com/TryGhost/Themes/blob/main/packages/london/assets/css/vars.css#L9) but it does not effect the background, because there the text color is uses, see https://github.com/TryGhost/Themes/blob/main/packages/_shared/assets/css/v2/general/global.css#L37

**Comment by minimaluminium** [comment]
Hey @Nightapes, thanks for your feedbacks!

The dropdown and the mobile menu issues should be fixed by now. About the CSS custom property `--color-bg`, it was a leftover and should've been removed. Our official themes mostly use custom properties from the shared assets, however, some of them override (or use new ones) depending on the theme design. It's best to inspect the theme CSS in your browser and see which properties are being used, and update them respectively.

For example, the background color is using `--color-white` custom property, and you should override this while you're adding dark mode CSS to your theme.

![CleanShot 2023-03-02 at 3 16 37@2x](https://user-images.githubusercontent.com/1418797/222357809-b62046d4-e888-46a1-80e9-2f2febf3d0de.png)
